name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - working-directory: nginx-1.17
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/tomy0000000/docker-registery/nginx:1.17-$(date +%s)
