name: "Integrated Dev Latest"

on:
  push:
    paths:
      - "Dockerfiles/integrated-dev/**"
      - "!Dockerfiles/integrated-dev/latest/README.md"
    branches:
      - "master"
    tags:
      - "integrated-dev-latest-*"

env:
  IMAGE_NAME: "integrated-dev"
  BASE_VERSION: "latest"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # build-push-action@v2 does not support path for git context yet
      # manually copy context to root
      - name: Copy context for docker build
        run: cp -r Dockerfiles/${{ env.IMAGE_NAME }}/${{ env.BASE_VERSION }}/. .
      - name: Convert repository name to lowercase
        run: echo "GITHUB_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Compose tag for build test
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: echo "IMAGE_TAG=${{ env.BASE_VERSION }}" >> $GITHUB_ENV
      - name: Compose tag for release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: echo "IMAGE_TAG=$(echo ${{ github.ref }} | cut -d '/' -f 3 | sed -En 's/^${{ env.IMAGE_NAME }}-(.*)/\1/p')" >> $GITHUB_ENV
      - name: Login to DockerHub
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
  # # 2FA enabled is not supported yet, fix this someday
  # update-docker-hub-readme:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Update repository description
  #       uses: peter-evans/dockerhub-description@v2
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #         repository: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
  #         readme-filepath: Dockerfiles/${{ env.IMAGE_NAME }}/${{ env.BASE_VERSION }}/README.md
