name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: nginx:1.17
  PUSH_IMAGE_NAME: docker.pkg.github.com/${{ github.repository }}/nginx:1.17-$(date +%s)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME
      working-directory: nginx-1.17
    - name: Log into registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
    - name: Push image
      run: |
        # Change all uppercase to lowercase
        PUSH_IMAGE_NAME=$(echo $PUSH_IMAGE_NAME | tr '[A-Z]' '[a-z]')
        echo Push $PUSH_IMAGE_NAME
        
        # Push
        docker tag $IMAGE_NAME $PUSH_IMAGE_NAME
        docker push $BUILT_IMAGE
