name: nginx

on:
  push:
    paths: Dockerfiles/nginx-1.17/*
    tags:
    - "*"

env:
  IMAGE_NAME: nginx:1.17

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          repository: ${{ github.repository }}/${{ github.workflow }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: 1.17
          path: Dockerfiles/nginx-1.17
  github-package:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          repository: ${{ github.repository }}
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          tags: 1.17
          path: Dockerfiles/nginx-1.17
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Build Image
  #     run: docker build . --file Dockerfile --tag $IMAGE_NAME
  #     working-directory: Dockerfiles/nginx-1.17
  #   - name: Log into registry
  #     run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
  #   - name: Push image
  #     run: |
  #       # Naming
  #       IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
  #       IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')-$(date +%s)
  #       echo Push $IMAGE_ID
        
  #       # Push
  #       docker tag $IMAGE_NAME $IMAGE_ID
  #       docker push $IMAGE_ID
