name: nginx

on:
  push:
    paths: Dockerfiles/nginx-1.17/*
    tags:
    - "*"

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          repository: ${{ github.repository_owner }}/${{ github.workflow }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: 1.17
          path: ./Dockerfiles/nginx-1.17
  github-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Convert repository name to lowercase
        run: echo ::set-env name=IMAGE_REPOSITORY::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
      - name: Build and Push to Github Package
        uses: docker/build-push-action@v1
        with:
          repository: ${{ env.IMAGE_REPOSITORY }}
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          tags: 1.17
          path: ./Dockerfiles/nginx-1.17
