name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: docker.pkg.github.com/${{ github.repository }}/nginx
  IMAGE_VERSION: 1.17

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Image
      run: |
        IMAGE_NAME=$(echo $IMAGE_NAME | tr '[A-Z]' '[a-z]') # Change all uppercase to lowercase
        BUILT_IMAGE=$IMAGE_NAME:$IMAGE_VERSION-$(date +%s)
        docker build . --file Dockerfile --tag $BUILT_IMAGE
      working-directory: nginx-1.17
    - name: Log into registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
    - name: Push image
      run: docker push $BUILT_IMAGE
