name: nginx

on: push

# on:
#   push:
#     paths: Dockerfiles/nginx-1.17/*

jobs:
  checkout-and-conversions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Convert repository name to lowercase
        run: echo ::set-env name=GITHUB_REPOSITORY::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
      - name: Convert tag to version
        run: echo ::set-env name=IMAGE_VERSION::$(echo ${{ github.ref }} | cut -d"/" -f3 | cut -d"-" -f2)
  docker-hub:
    runs-on: ubuntu-latest
    needs: checkout-and-conversions
    steps:
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          repository: ${{ github.repository_owner }}/${{ github.workflow }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: 1.17-${{ env.IMAGE_VERSION }}
          path: Dockerfiles/nginx-1.17
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
  github-package:
    runs-on: ubuntu-latest
    needs: checkout-and-conversions
    steps:
      - name: Build and Push to Github Package
        uses: docker/build-push-action@v1
        with:
          repository: ${{ env.GITHUB_REPOSITORY }}/${{ github.workflow }}
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          tags: 1.17-${{ env.IMAGE_VERSION }}
          path: Dockerfiles/nginx-1.17
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
